# fly.toml app configuration file generated for precis-api on 2023-10-16T14:43:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "precis-api"
primary_region = "lhr"

[build]
  builder = "heroku/buildpacks:latest"
  # builder = "paketobuildpacks/builder:base"

[processes]
  app = “python app.py”

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
